package entidades_basededatos;
// Generated 31/08/2022 20:07:14 by Hibernate Tools 4.3.1



/**
 * Acercade generated by hbm2java
 */
public class Acercade  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String telefono;
     private String ubicacion;
     private String descripcion;

    public Acercade() {
    }

	
    public Acercade(int id) {
        this.id = id;
    }
    public Acercade(int id, String nombre, String telefono, String ubicacion, String descripcion) {
       this.id = id;
       this.nombre = nombre;
       this.telefono = telefono;
       this.ubicacion = ubicacion;
       this.descripcion = descripcion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


