package entidades_basededatos;
// Generated 31/08/2022 20:07:14 by Hibernate Tools 4.3.1



/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private int iddetventa;
     private Venta venta;
     private Integer cantidad;

    public Detalleventa() {
    }

	
    public Detalleventa(int iddetventa) {
        this.iddetventa = iddetventa;
    }
    public Detalleventa(int iddetventa, Venta venta, Integer cantidad) {
       this.iddetventa = iddetventa;
       this.venta = venta;
       this.cantidad = cantidad;
    }
   
    public int getIddetventa() {
        return this.iddetventa;
    }
    
    public void setIddetventa(int iddetventa) {
        this.iddetventa = iddetventa;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


