package entidades_basededatos;
// Generated 31/08/2022 20:07:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombre;
     private String apellido;
     private String cedula;
     private String tipousuario;
     private String email;
     private String telefono;
     private String contrasenna;
     private byte[] imagen;
     private String nombrefoto;
     private Set ventas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, String cedula) {
        this.idusuario = idusuario;
        this.cedula = cedula;
    }
    public Usuario(int idusuario, String nombre, String apellido, String cedula, String tipousuario, String email, String telefono, String contrasenna, byte[] imagen, String nombrefoto, Set ventas) {
       this.idusuario = idusuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.cedula = cedula;
       this.tipousuario = tipousuario;
       this.email = email;
       this.telefono = telefono;
       this.contrasenna = contrasenna;
       this.imagen = imagen;
       this.nombrefoto = nombrefoto;
       this.ventas = ventas;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(String tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getContrasenna() {
        return this.contrasenna;
    }
    
    public void setContrasenna(String contrasenna) {
        this.contrasenna = contrasenna;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public String getNombrefoto() {
        return this.nombrefoto;
    }
    
    public void setNombrefoto(String nombrefoto) {
        this.nombrefoto = nombrefoto;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


