package entidades_basededatos;
// Generated 31/08/2022 20:07:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idventa;
     private Producto producto;
     private Usuario usuario;
     private Date fecha;
     private Double monto;
     private Integer cantidad;
     private Set detalleventas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(int idventa, Usuario usuario) {
        this.idventa = idventa;
        this.usuario = usuario;
    }
    public Venta(int idventa, Producto producto, Usuario usuario, Date fecha, Double monto, Integer cantidad, Set detalleventas) {
       this.idventa = idventa;
       this.producto = producto;
       this.usuario = usuario;
       this.fecha = fecha;
       this.monto = monto;
       this.cantidad = cantidad;
       this.detalleventas = detalleventas;
    }
   
    public int getIdventa() {
        return this.idventa;
    }
    
    public void setIdventa(int idventa) {
        this.idventa = idventa;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


