package entidades_database;
// Generated 18/02/2022 06:54:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private BigDecimal iddetalleventa;
     private Producto producto;
     private Venta venta;
     private Integer cantidad;
     private Double precioventa;

    public Detalleventa() {
    }

	
    public Detalleventa(BigDecimal iddetalleventa) {
        this.iddetalleventa = iddetalleventa;
    }
    public Detalleventa(BigDecimal iddetalleventa, Producto producto, Venta venta, Integer cantidad, Double precioventa) {
       this.iddetalleventa = iddetalleventa;
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
       this.precioventa = precioventa;
    }
   
    public BigDecimal getIddetalleventa() {
        return this.iddetalleventa;
    }
    
    public void setIddetalleventa(BigDecimal iddetalleventa) {
        this.iddetalleventa = iddetalleventa;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecioventa() {
        return this.precioventa;
    }
    
    public void setPrecioventa(Double precioventa) {
        this.precioventa = precioventa;
    }




}


