package entidades_database;
// Generated 18/02/2022 06:54:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int productoid;
     private String nombre;
     private Double precio;
     private Integer stock;
     private String descripcion;
     private Set<Detalleventa> detalleventas = new HashSet<Detalleventa>(0);
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Producto() {
    }

	
    public Producto(int productoid) {
        this.productoid = productoid;
    }
    public Producto(int productoid, String nombre, Double precio, Integer stock, String descripcion, Set<Detalleventa> detalleventas, Set<Venta> ventas) {
       this.productoid = productoid;
       this.nombre = nombre;
       this.precio = precio;
       this.stock = stock;
       this.descripcion = descripcion;
       this.detalleventas = detalleventas;
       this.ventas = ventas;
    }
   
    public int getProductoid() {
        return this.productoid;
    }
    
    public void setProductoid(int productoid) {
        this.productoid = productoid;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Detalleventa> getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set<Detalleventa> detalleventas) {
        this.detalleventas = detalleventas;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


