package entidades_database;
// Generated 18/02/2022 06:54:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idventa;
     private Producto producto;
     private Date fecha;
     private Set<Detalleventa> detalleventas = new HashSet<Detalleventa>(0);

    public Venta() {
    }

	
    public Venta(int idventa) {
        this.idventa = idventa;
    }
    public Venta(int idventa, Producto producto, Date fecha, Set<Detalleventa> detalleventas) {
       this.idventa = idventa;
       this.producto = producto;
       this.fecha = fecha;
       this.detalleventas = detalleventas;
    }
   
    public int getIdventa() {
        return this.idventa;
    }
    
    public void setIdventa(int idventa) {
        this.idventa = idventa;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Detalleventa> getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set<Detalleventa> detalleventas) {
        this.detalleventas = detalleventas;
    }




}


